export { default as Svg2NdBubble } from './2NdBubble'
export { default as BoardForIcons } from './BoardForIcons'
export { default as BubblewhatCanWeSurveForYou } from './Bubble (whatCanWeSurveForYou)'
export { default as ClientsBubble } from './ClientsBubble'
export { default as FooterLogo } from './FooterLogo'
export { default as Icons1 } from './Icons (1)'
export { default as Icons2 } from './Icons (2)'
export { default as Icons3 } from './Icons (3)'
export { default as Icons4 } from './Icons (4)'
export { default as Icons5 } from './Icons (5)'
export { default as Icons6 } from './Icons (6)'
export { default as LandingPageBannerMain } from './LandingPageBannerMain'
export { default as LastTeamBanner } from './LastTeamBanner'
export { default as PicFor2NdBubble } from './PicFor2NdBubble'
export { default as TeamBubble } from './TeamBubble'